# Generated by Django 4.2.6 on 2024-01-13 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autenticacao', '0001_initial'),
        ('agendamento', '0001_initial'),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='candidato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos', to='autenticacao.candidato', verbose_name='Candidato'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='estabelecimento_saude',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos', to='base.estabelecimentosaude', verbose_name='Estabelecimento de Saúde'),
        ),
    ]
