# Generated by Django 4.2.6 on 2024-01-13 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstabelecimentoSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('codigo_cnes', models.CharField(max_length=7)),
            ],
            options={
                'verbose_name': 'Estabelecimento de Saúde',
                'verbose_name_plural': 'Estabelecimentos de Saúde',
            },
        ),
        migrations.CreateModel(
            name='GrupoAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('codigo_si_pni', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Grupo de Atendimento',
                'verbose_name_plural': 'Grupos de Atendimento',
            },
        ),
    ]
