# Generated by Django 4.2.6 on 2024-01-03 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Nome Completo'),
        ),
    ]
