# Generated by Django 4.2.6 on 2024-01-03 04:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0002_alter_candidato_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='candidato',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')
        ),
    ]
